<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFrameworks>net10.0;net10.0-windows</TargetFrameworks>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<BuiltInComInteropSupport>true</BuiltInComInteropSupport>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
		<EnableWindowsTargeting>true</EnableWindowsTargeting>
		<AssemblyName>screengrab</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" Version="12.1.2" />
		<PackageReference Include="Avalonia.Desktop" Version="12.1.2" />
		<PackageReference Include="Avalonia.Skia" Version="12.1.2" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ScreenGrab.Core\ScreenGrab.Core.csproj" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0-windows'">
		<ProjectReference Include="..\ScreenGrab.Windows\ScreenGrab.Windows.csproj" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
		<ProjectReference Include="..\ScreenGrab.Linux\ScreenGrab.Linux.csproj" />
	</ItemGroup>

	<ItemGroup>
		<AvaloniaResource Include="Assets\**" />
	</ItemGroup>

</Project>
